name: Order
description: Ask to create any existing unit from the campaign or a completely new unit concept.
title: "[Заказ] - <Write your title>"
labels: [order]
body:
- type: dropdown
  id: unittype
  attributes:
    label: Type of unit
    multiple: false
    options:
      - Unit
      - Structure
      - Hero
  validations:
    required: true
- type: dropdown
  id: locale
  attributes:
    label: Locale
    multiple: true
    options:
      - enUS
      - ruRU
  validations:
    required: true
- type: textarea
  attributes:
    label: About info
    description: Anything you’d like to say about your order or your unit.
- type: textarea
  attributes:
    label: Weapons
    description: A list of weapons your unit should have
- type: textarea
  attributes:
    label: Abilities
    description: A list of abilities your unit should have